DROP TABLE translation_logs_test;
CREATE TABLE IF NOT EXISTS translation_logs_test (
    id integer primary key generated by default as identity,
    ip varchar,
    input_text varchar,
    translated_text varchar
);